### ISSUE TITLE
Pet follow command while in combat does not work, along with general pet responsiveness being really sluggish

### ISSUE THREAD

**Issue by watchyoursixx** [watchyoursixx/hunter-tbc#61]
with the latest beta patch 38364 pets are no longer able to return with petfollow command either macroed or the button.

Pet responsiveness as well (the pet following the character by their side specifically) is really sluggish for some reason.

**Comment by watchyoursixx** [comment]
Fixed as of build 38521 (specifically pet follow command)

**Comment by watchyoursixx** [comment]
just kidding, I must have tested it wrong.

When pet is attacking a target, you cannot bring it back to your side with petfollow button or macro. The pet does stop attacking though

**Comment by klingo** [comment]
Still broken on the PTR as of today. Pet only comes back once you drop combat.

**Comment by watchyoursixx** [comment]
fixed on live 38709 and beta 38739
